//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekovnaSostojbaAKNTestCorrected.TekovnaSostojbaAKNTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InteropFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DataAccessLibrary")]
    [System.SerializableAttribute()]
    public partial class InteropFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interop.org/", ConfigurationName="TekovnaSostojbaAKNTest.ICRM_TS_AKN")]
    public interface ICRM_TS_AKN {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ICRM_TS_AKN/Get_TS_AKN", ReplyAction="http://interop.org/ICRM_TS_AKN/Get_TS_AKNResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TekovnaSostojbaAKNTestCorrected.TekovnaSostojbaAKNTest.InteropFault), Action="http://interop.org/ICRM_TS_AKN/Get_TS_AKNInteropFaultFault", Name="InteropFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DataAccessLibrary")]
        string Get_TS_AKN(string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ICRM_TS_AKN/Get_TS_AKN", ReplyAction="http://interop.org/ICRM_TS_AKN/Get_TS_AKNResponse")]
        System.Threading.Tasks.Task<string> Get_TS_AKNAsync(string param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRM_TS_AKNChannel : TekovnaSostojbaAKNTestCorrected.TekovnaSostojbaAKNTest.ICRM_TS_AKN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRM_TS_AKNClient : System.ServiceModel.ClientBase<TekovnaSostojbaAKNTestCorrected.TekovnaSostojbaAKNTest.ICRM_TS_AKN>, TekovnaSostojbaAKNTestCorrected.TekovnaSostojbaAKNTest.ICRM_TS_AKN {
        
        public CRM_TS_AKNClient() {
        }
        
        public CRM_TS_AKNClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRM_TS_AKNClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRM_TS_AKNClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRM_TS_AKNClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get_TS_AKN(string param) {
            return base.Channel.Get_TS_AKN(param);
        }
        
        public System.Threading.Tasks.Task<string> Get_TS_AKNAsync(string param) {
            return base.Channel.Get_TS_AKNAsync(param);
        }
    }
}
