//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRRMTest.AdapterListOfChangesTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interop.org/", ConfigurationName="AdapterListOfChangesTest.IListOfChangesCUTest")]
    public interface IListOfChangesCUTest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IListOfChangesCUTest/GetListOfChangesCU", ReplyAction="http://interop.org/IListOfChangesCUTest/GetListOfChangesCUResponse")]
        string GetListOfChangesCU(string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IListOfChangesCUTest/GetListOfChangesCU", ReplyAction="http://interop.org/IListOfChangesCUTest/GetListOfChangesCUResponse")]
        System.Threading.Tasks.Task<string> GetListOfChangesCUAsync(string param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListOfChangesCUTestChannel : CRRMTest.AdapterListOfChangesTest.IListOfChangesCUTest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListOfChangesCUTestClient : System.ServiceModel.ClientBase<CRRMTest.AdapterListOfChangesTest.IListOfChangesCUTest>, CRRMTest.AdapterListOfChangesTest.IListOfChangesCUTest {
        
        public ListOfChangesCUTestClient() {
        }
        
        public ListOfChangesCUTestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListOfChangesCUTestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListOfChangesCUTestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListOfChangesCUTestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetListOfChangesCU(string param) {
            return base.Channel.GetListOfChangesCU(param);
        }
        
        public System.Threading.Tasks.Task<string> GetListOfChangesCUAsync(string param) {
            return base.Channel.GetListOfChangesCUAsync(param);
        }
    }
}
