//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRRMTest.AdapterTSFull {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interop.org/", ConfigurationName="AdapterTSFull.ICRMService")]
    public interface ICRMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ICRMService/GetTekovnaSostojba", ReplyAction="http://interop.org/ICRMService/GetTekovnaSostojbaResponse")]
        string GetTekovnaSostojba(string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ICRMService/GetTekovnaSostojba", ReplyAction="http://interop.org/ICRMService/GetTekovnaSostojbaResponse")]
        System.Threading.Tasks.Task<string> GetTekovnaSostojbaAsync(string param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRMServiceChannel : CRRMTest.AdapterTSFull.ICRMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRMServiceClient : System.ServiceModel.ClientBase<CRRMTest.AdapterTSFull.ICRMService>, CRRMTest.AdapterTSFull.ICRMService {
        
        public CRMServiceClient() {
        }
        
        public CRMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTekovnaSostojba(string param) {
            return base.Channel.GetTekovnaSostojba(param);
        }
        
        public System.Threading.Tasks.Task<string> GetTekovnaSostojbaAsync(string param) {
            return base.Channel.GetTekovnaSostojbaAsync(param);
        }
    }
}
