//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadTestClient.MzTV_OdobrenieGradbaDozovla {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InteropOutputViewModel", Namespace="https://www.gradezna-dozvola.mk/Services/")]
    [System.SerializableAttribute()]
    public partial class InteropOutputViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadTestClient.MzTV_OdobrenieGradbaDozovla.ArrayOfString InvestorsField;
        
        private System.DateTime SendDateField;
        
        private System.DateTime ArchiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConstructionDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConstructionTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConstructionAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadTestClient.MzTV_OdobrenieGradbaDozovla.InteropRequestMunicipalityViewModel[] MunicipalitiesField;
        
        private System.Nullable<System.DateTime> EffectDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadTestClient.MzTV_OdobrenieGradbaDozovla.InteropDocumentsViewModel[] DocumentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public LoadTestClient.MzTV_OdobrenieGradbaDozovla.ArrayOfString Investors {
            get {
                return this.InvestorsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorsField, value) != true)) {
                    this.InvestorsField = value;
                    this.RaisePropertyChanged("Investors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime ArchiveDate {
            get {
                return this.ArchiveDateField;
            }
            set {
                if ((this.ArchiveDateField.Equals(value) != true)) {
                    this.ArchiveDateField = value;
                    this.RaisePropertyChanged("ArchiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ConstructionDescription {
            get {
                return this.ConstructionDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstructionDescriptionField, value) != true)) {
                    this.ConstructionDescriptionField = value;
                    this.RaisePropertyChanged("ConstructionDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ConstructionTypeName {
            get {
                return this.ConstructionTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstructionTypeNameField, value) != true)) {
                    this.ConstructionTypeNameField = value;
                    this.RaisePropertyChanged("ConstructionTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ConstructionAddress {
            get {
                return this.ConstructionAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstructionAddressField, value) != true)) {
                    this.ConstructionAddressField = value;
                    this.RaisePropertyChanged("ConstructionAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public LoadTestClient.MzTV_OdobrenieGradbaDozovla.InteropRequestMunicipalityViewModel[] Municipalities {
            get {
                return this.MunicipalitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipalitiesField, value) != true)) {
                    this.MunicipalitiesField = value;
                    this.RaisePropertyChanged("Municipalities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> EffectDate {
            get {
                return this.EffectDateField;
            }
            set {
                if ((this.EffectDateField.Equals(value) != true)) {
                    this.EffectDateField = value;
                    this.RaisePropertyChanged("EffectDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public LoadTestClient.MzTV_OdobrenieGradbaDozovla.InteropDocumentsViewModel[] Documents {
            get {
                return this.DocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentsField, value) != true)) {
                    this.DocumentsField = value;
                    this.RaisePropertyChanged("Documents");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://www.gradezna-dozvola.mk/Services/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InteropRequestMunicipalityViewModel", Namespace="https://www.gradezna-dozvola.mk/Services/")]
    [System.SerializableAttribute()]
    public partial class InteropRequestMunicipalityViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipalityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadTestClient.MzTV_OdobrenieGradbaDozovla.InteropCadastreMunicipalityViewModel[] CadastreMunicipalitiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MunicipalityName {
            get {
                return this.MunicipalityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipalityNameField, value) != true)) {
                    this.MunicipalityNameField = value;
                    this.RaisePropertyChanged("MunicipalityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public LoadTestClient.MzTV_OdobrenieGradbaDozovla.InteropCadastreMunicipalityViewModel[] CadastreMunicipalities {
            get {
                return this.CadastreMunicipalitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CadastreMunicipalitiesField, value) != true)) {
                    this.CadastreMunicipalitiesField = value;
                    this.RaisePropertyChanged("CadastreMunicipalities");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InteropDocumentsViewModel", Namespace="https://www.gradezna-dozvola.mk/Services/")]
    [System.SerializableAttribute()]
    public partial class InteropDocumentsViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentBytesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] ContentBytes {
            get {
                return this.ContentBytesField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentBytesField, value) != true)) {
                    this.ContentBytesField = value;
                    this.RaisePropertyChanged("ContentBytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InteropCadastreMunicipalityViewModel", Namespace="https://www.gradezna-dozvola.mk/Services/")]
    [System.SerializableAttribute()]
    public partial class InteropCadastreMunicipalityViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Ko {
            get {
                return this.KoField;
            }
            set {
                if ((object.ReferenceEquals(this.KoField, value) != true)) {
                    this.KoField = value;
                    this.RaisePropertyChanged("Ko");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Kp {
            get {
                return this.KpField;
            }
            set {
                if ((object.ReferenceEquals(this.KpField, value) != true)) {
                    this.KpField = value;
                    this.RaisePropertyChanged("Kp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MzTV_OdobrenieGradbaDozovla.IMzTVAdapter")]
    public interface IMzTVAdapter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMzTVAdapter/ConsPerm", ReplyAction="http://tempuri.org/IMzTVAdapter/ConsPermResponse")]
        LoadTestClient.MzTV_OdobrenieGradbaDozovla.InteropOutputViewModel ConsPerm(string archiveNumber, string constructionTypeId, string municipalityId, string sendDate, string getDocuments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMzTVAdapter/ConsPerm", ReplyAction="http://tempuri.org/IMzTVAdapter/ConsPermResponse")]
        System.Threading.Tasks.Task<LoadTestClient.MzTV_OdobrenieGradbaDozovla.InteropOutputViewModel> ConsPermAsync(string archiveNumber, string constructionTypeId, string municipalityId, string sendDate, string getDocuments);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMzTVAdapterChannel : LoadTestClient.MzTV_OdobrenieGradbaDozovla.IMzTVAdapter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MzTVAdapterClient : System.ServiceModel.ClientBase<LoadTestClient.MzTV_OdobrenieGradbaDozovla.IMzTVAdapter>, LoadTestClient.MzTV_OdobrenieGradbaDozovla.IMzTVAdapter {
        
        public MzTVAdapterClient() {
        }
        
        public MzTVAdapterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MzTVAdapterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MzTVAdapterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MzTVAdapterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LoadTestClient.MzTV_OdobrenieGradbaDozovla.InteropOutputViewModel ConsPerm(string archiveNumber, string constructionTypeId, string municipalityId, string sendDate, string getDocuments) {
            return base.Channel.ConsPerm(archiveNumber, constructionTypeId, municipalityId, sendDate, getDocuments);
        }
        
        public System.Threading.Tasks.Task<LoadTestClient.MzTV_OdobrenieGradbaDozovla.InteropOutputViewModel> ConsPermAsync(string archiveNumber, string constructionTypeId, string municipalityId, string sendDate, string getDocuments) {
            return base.Channel.ConsPermAsync(archiveNumber, constructionTypeId, municipalityId, sendDate, getDocuments);
        }
    }
}
