//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.SingleCustDocTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleCustomsDocumentOutput", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Models.SingleCustomsDocument")]
    [System.SerializableAttribute()]
    public partial class SingleCustomsDocumentOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestApp.SingleCustDocTest.SCDExporterData ExporterDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestApp.SingleCustDocTest.SCDGeneralData GeneralDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestApp.SingleCustDocTest.SCDImporterData ImporterDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestApp.SingleCustDocTest.SCDItemData[] ItemDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestApp.SingleCustDocTest.SCDExporterData ExporterData {
            get {
                return this.ExporterDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ExporterDataField, value) != true)) {
                    this.ExporterDataField = value;
                    this.RaisePropertyChanged("ExporterData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestApp.SingleCustDocTest.SCDGeneralData GeneralData {
            get {
                return this.GeneralDataField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralDataField, value) != true)) {
                    this.GeneralDataField = value;
                    this.RaisePropertyChanged("GeneralData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestApp.SingleCustDocTest.SCDImporterData ImporterData {
            get {
                return this.ImporterDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImporterDataField, value) != true)) {
                    this.ImporterDataField = value;
                    this.RaisePropertyChanged("ImporterData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestApp.SingleCustDocTest.SCDItemData[] ItemData {
            get {
                return this.ItemDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDataField, value) != true)) {
                    this.ItemDataField = value;
                    this.RaisePropertyChanged("ItemData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SCDExporterData", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Models.SingleCustomsDocument")]
    [System.SerializableAttribute()]
    public partial class SCDExporterData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderAddressPart1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderAddressPart2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderPostalCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderAddressPart1 {
            get {
                return this.SenderAddressPart1Field;
            }
            set {
                if ((object.ReferenceEquals(this.SenderAddressPart1Field, value) != true)) {
                    this.SenderAddressPart1Field = value;
                    this.RaisePropertyChanged("SenderAddressPart1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderAddressPart2 {
            get {
                return this.SenderAddressPart2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SenderAddressPart2Field, value) != true)) {
                    this.SenderAddressPart2Field = value;
                    this.RaisePropertyChanged("SenderAddressPart2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderName {
            get {
                return this.SenderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderNameField, value) != true)) {
                    this.SenderNameField = value;
                    this.RaisePropertyChanged("SenderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderPlace {
            get {
                return this.SenderPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderPlaceField, value) != true)) {
                    this.SenderPlaceField = value;
                    this.RaisePropertyChanged("SenderPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderPostalCode {
            get {
                return this.SenderPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderPostalCodeField, value) != true)) {
                    this.SenderPostalCodeField = value;
                    this.RaisePropertyChanged("SenderPostalCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SCDGeneralData", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Models.SingleCustomsDocument")]
    [System.SerializableAttribute()]
    public partial class SCDGeneralData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeclarantCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeclatarionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryTermsSituationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExciseStoreCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExportingConditionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExportingConditionPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExportingCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImportExportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImporterEDBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityOfVehicleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcedureTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationOfVehicleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationSeriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderEDBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalInvoiceAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeclarantCode {
            get {
                return this.DeclarantCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclarantCodeField, value) != true)) {
                    this.DeclarantCodeField = value;
                    this.RaisePropertyChanged("DeclarantCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeclatarionType {
            get {
                return this.DeclatarionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclatarionTypeField, value) != true)) {
                    this.DeclatarionTypeField = value;
                    this.RaisePropertyChanged("DeclatarionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryTermsSituationCode {
            get {
                return this.DeliveryTermsSituationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryTermsSituationCodeField, value) != true)) {
                    this.DeliveryTermsSituationCodeField = value;
                    this.RaisePropertyChanged("DeliveryTermsSituationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCountry {
            get {
                return this.DestinationCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationCountryField, value) != true)) {
                    this.DestinationCountryField = value;
                    this.RaisePropertyChanged("DestinationCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExciseStoreCode {
            get {
                return this.ExciseStoreCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExciseStoreCodeField, value) != true)) {
                    this.ExciseStoreCodeField = value;
                    this.RaisePropertyChanged("ExciseStoreCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExportingConditionCode {
            get {
                return this.ExportingConditionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExportingConditionCodeField, value) != true)) {
                    this.ExportingConditionCodeField = value;
                    this.RaisePropertyChanged("ExportingConditionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExportingConditionPlace {
            get {
                return this.ExportingConditionPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.ExportingConditionPlaceField, value) != true)) {
                    this.ExportingConditionPlaceField = value;
                    this.RaisePropertyChanged("ExportingConditionPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExportingCountry {
            get {
                return this.ExportingCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ExportingCountryField, value) != true)) {
                    this.ExportingCountryField = value;
                    this.RaisePropertyChanged("ExportingCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImportExport {
            get {
                return this.ImportExportField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportExportField, value) != true)) {
                    this.ImportExportField = value;
                    this.RaisePropertyChanged("ImportExport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImporterEDB {
            get {
                return this.ImporterEDBField;
            }
            set {
                if ((object.ReferenceEquals(this.ImporterEDBField, value) != true)) {
                    this.ImporterEDBField = value;
                    this.RaisePropertyChanged("ImporterEDB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumberField, value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalityOfVehicle {
            get {
                return this.NationalityOfVehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityOfVehicleField, value) != true)) {
                    this.NationalityOfVehicleField = value;
                    this.RaisePropertyChanged("NationalityOfVehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCountry {
            get {
                return this.OriginCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginCountryField, value) != true)) {
                    this.OriginCountryField = value;
                    this.RaisePropertyChanged("OriginCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcedureType {
            get {
                return this.ProcedureTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcedureTypeField, value) != true)) {
                    this.ProcedureTypeField = value;
                    this.RaisePropertyChanged("ProcedureType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferentNumber {
            get {
                return this.ReferentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferentNumberField, value) != true)) {
                    this.ReferentNumberField = value;
                    this.RaisePropertyChanged("ReferentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationDate {
            get {
                return this.RegistrationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationDateField, value) != true)) {
                    this.RegistrationDateField = value;
                    this.RaisePropertyChanged("RegistrationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationNumber {
            get {
                return this.RegistrationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationNumberField, value) != true)) {
                    this.RegistrationNumberField = value;
                    this.RaisePropertyChanged("RegistrationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationOfVehicle {
            get {
                return this.RegistrationOfVehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationOfVehicleField, value) != true)) {
                    this.RegistrationOfVehicleField = value;
                    this.RaisePropertyChanged("RegistrationOfVehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationSeries {
            get {
                return this.RegistrationSeriesField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationSeriesField, value) != true)) {
                    this.RegistrationSeriesField = value;
                    this.RaisePropertyChanged("RegistrationSeries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderEDB {
            get {
                return this.SenderEDBField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderEDBField, value) != true)) {
                    this.SenderEDBField = value;
                    this.RaisePropertyChanged("SenderEDB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalInvoiceAmount {
            get {
                return this.TotalInvoiceAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalInvoiceAmountField, value) != true)) {
                    this.TotalInvoiceAmountField = value;
                    this.RaisePropertyChanged("TotalInvoiceAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueData {
            get {
                return this.ValueDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueDataField, value) != true)) {
                    this.ValueDataField = value;
                    this.RaisePropertyChanged("ValueData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SCDImporterData", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Models.SingleCustomsDocument")]
    [System.SerializableAttribute()]
    public partial class SCDImporterData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImporterAddressPart1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImporterAddressPart2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImporterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImporterPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImporterPostalCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImporterAddressPart1 {
            get {
                return this.ImporterAddressPart1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ImporterAddressPart1Field, value) != true)) {
                    this.ImporterAddressPart1Field = value;
                    this.RaisePropertyChanged("ImporterAddressPart1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImporterAddressPart2 {
            get {
                return this.ImporterAddressPart2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ImporterAddressPart2Field, value) != true)) {
                    this.ImporterAddressPart2Field = value;
                    this.RaisePropertyChanged("ImporterAddressPart2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImporterName {
            get {
                return this.ImporterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImporterNameField, value) != true)) {
                    this.ImporterNameField = value;
                    this.RaisePropertyChanged("ImporterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImporterPlace {
            get {
                return this.ImporterPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.ImporterPlaceField, value) != true)) {
                    this.ImporterPlaceField = value;
                    this.RaisePropertyChanged("ImporterPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImporterPostalCode {
            get {
                return this.ImporterPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImporterPostalCodeField, value) != true)) {
                    this.ImporterPostalCodeField = value;
                    this.RaisePropertyChanged("ImporterPostalCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SCDItemData", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Models.SingleCustomsDocument")]
    [System.SerializableAttribute()]
    public partial class SCDItemData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryOfOriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionOfGoodsPart1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionOfGoodsPart2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionOfGoodsPart3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrossMassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatisticalValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TariffTagPart1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TariffTagPart2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryOfOrigin {
            get {
                return this.CountryOfOriginField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryOfOriginField, value) != true)) {
                    this.CountryOfOriginField = value;
                    this.RaisePropertyChanged("CountryOfOrigin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionOfGoodsPart1 {
            get {
                return this.DescriptionOfGoodsPart1Field;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionOfGoodsPart1Field, value) != true)) {
                    this.DescriptionOfGoodsPart1Field = value;
                    this.RaisePropertyChanged("DescriptionOfGoodsPart1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionOfGoodsPart2 {
            get {
                return this.DescriptionOfGoodsPart2Field;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionOfGoodsPart2Field, value) != true)) {
                    this.DescriptionOfGoodsPart2Field = value;
                    this.RaisePropertyChanged("DescriptionOfGoodsPart2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionOfGoodsPart3 {
            get {
                return this.DescriptionOfGoodsPart3Field;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionOfGoodsPart3Field, value) != true)) {
                    this.DescriptionOfGoodsPart3Field = value;
                    this.RaisePropertyChanged("DescriptionOfGoodsPart3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrossMass {
            get {
                return this.GrossMassField;
            }
            set {
                if ((object.ReferenceEquals(this.GrossMassField, value) != true)) {
                    this.GrossMassField = value;
                    this.RaisePropertyChanged("GrossMass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Preference {
            get {
                return this.PreferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferenceField, value) != true)) {
                    this.PreferenceField = value;
                    this.RaisePropertyChanged("Preference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatisticalValue {
            get {
                return this.StatisticalValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StatisticalValueField, value) != true)) {
                    this.StatisticalValueField = value;
                    this.RaisePropertyChanged("StatisticalValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TariffTagPart1 {
            get {
                return this.TariffTagPart1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TariffTagPart1Field, value) != true)) {
                    this.TariffTagPart1Field = value;
                    this.RaisePropertyChanged("TariffTagPart1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TariffTagPart2 {
            get {
                return this.TariffTagPart2Field;
            }
            set {
                if ((object.ReferenceEquals(this.TariffTagPart2Field, value) != true)) {
                    this.TariffTagPart2Field = value;
                    this.RaisePropertyChanged("TariffTagPart2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InteropFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DataAccessLibrary")]
    [System.SerializableAttribute()]
    public partial class InteropFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomsOfficeNumbers", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Models.SingleCustomsDocument")]
    [System.SerializableAttribute()]
    public partial class CustomsOfficeNumbers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomsOfficeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomsOfficeNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomsOfficeName {
            get {
                return this.CustomsOfficeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomsOfficeNameField, value) != true)) {
                    this.CustomsOfficeNameField = value;
                    this.RaisePropertyChanged("CustomsOfficeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomsOfficeNumber {
            get {
                return this.CustomsOfficeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomsOfficeNumberField, value) != true)) {
                    this.CustomsOfficeNumberField = value;
                    this.RaisePropertyChanged("CustomsOfficeNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interop.org/", ConfigurationName="SingleCustDocTest.ISingleCustDoc")]
    public interface ISingleCustDoc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ISingleCustDoc/GetSingleCustDoc", ReplyAction="http://interop.org/ISingleCustDoc/GetSingleCustDocResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestApp.SingleCustDocTest.InteropFault), Action="http://interop.org/ISingleCustDoc/GetSingleCustDocInteropFaultFault", Name="InteropFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DataAccessLibrary")]
        TestApp.SingleCustDocTest.SingleCustomsDocumentOutput GetSingleCustDoc(int year, long edbOfShippingCompany, int numberOfCustomsOffice, int regNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ISingleCustDoc/GetSingleCustDoc", ReplyAction="http://interop.org/ISingleCustDoc/GetSingleCustDocResponse")]
        System.Threading.Tasks.Task<TestApp.SingleCustDocTest.SingleCustomsDocumentOutput> GetSingleCustDocAsync(int year, long edbOfShippingCompany, int numberOfCustomsOffice, int regNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ISingleCustDoc/GetCustomsOfficeNumbers", ReplyAction="http://interop.org/ISingleCustDoc/GetCustomsOfficeNumbersResponse")]
        TestApp.SingleCustDocTest.CustomsOfficeNumbers[] GetCustomsOfficeNumbers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ISingleCustDoc/GetCustomsOfficeNumbers", ReplyAction="http://interop.org/ISingleCustDoc/GetCustomsOfficeNumbersResponse")]
        System.Threading.Tasks.Task<TestApp.SingleCustDocTest.CustomsOfficeNumbers[]> GetCustomsOfficeNumbersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISingleCustDocChannel : TestApp.SingleCustDocTest.ISingleCustDoc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SingleCustDocClient : System.ServiceModel.ClientBase<TestApp.SingleCustDocTest.ISingleCustDoc>, TestApp.SingleCustDocTest.ISingleCustDoc {
        
        public SingleCustDocClient() {
        }
        
        public SingleCustDocClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SingleCustDocClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingleCustDocClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingleCustDocClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestApp.SingleCustDocTest.SingleCustomsDocumentOutput GetSingleCustDoc(int year, long edbOfShippingCompany, int numberOfCustomsOffice, int regNumber) {
            return base.Channel.GetSingleCustDoc(year, edbOfShippingCompany, numberOfCustomsOffice, regNumber);
        }
        
        public System.Threading.Tasks.Task<TestApp.SingleCustDocTest.SingleCustomsDocumentOutput> GetSingleCustDocAsync(int year, long edbOfShippingCompany, int numberOfCustomsOffice, int regNumber) {
            return base.Channel.GetSingleCustDocAsync(year, edbOfShippingCompany, numberOfCustomsOffice, regNumber);
        }
        
        public TestApp.SingleCustDocTest.CustomsOfficeNumbers[] GetCustomsOfficeNumbers() {
            return base.Channel.GetCustomsOfficeNumbers();
        }
        
        public System.Threading.Tasks.Task<TestApp.SingleCustDocTest.CustomsOfficeNumbers[]> GetCustomsOfficeNumbersAsync() {
            return base.Channel.GetCustomsOfficeNumbersAsync();
        }
    }
}
