//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteropCS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InteropCS.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запис во пристапната листа со код за корисник &quot;{0}&quot; , код за провајдер &quot;{1}&quot; ,  код за сервис &quot;{2}&quot; и код за метод &quot;{3}&quot; постои во база.
        /// </summary>
        public static string DuplicateAccessMapping {
            get {
                return ResourceManager.GetString("DuplicateAccessMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Екстерен бас со код &quot;{0}&quot; постои во база.
        /// </summary>
        public static string DuplicateBus {
            get {
                return ResourceManager.GetString("DuplicateBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис со код &quot;{0}&quot; и код за учесник &quot;{1}&quot; постои во база.
        /// </summary>
        public static string DuplicateCSService {
            get {
                return ResourceManager.GetString("DuplicateCSService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог со трансакциски број &quot;{0}&quot; постои во база.
        /// </summary>
        public static string DuplicateMessageLog {
            get {
                return ResourceManager.GetString("DuplicateMessageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учесник со код &quot;{0}&quot; постои во база.
        /// </summary>
        public static string DuplicateParticipant {
            get {
                return ResourceManager.GetString("DuplicateParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корисник со име &quot;{0}&quot; постои во база.
        /// </summary>
        public static string DuplicateUserException {
            get {
                return ResourceManager.GetString("DuplicateUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Екстензија &apos;{0}&apos; не е валидна  за сертификат.
        /// </summary>
        public static string InvalidCertExtension {
            get {
                return ResourceManager.GetString("InvalidCertExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден сертификат (јавен клуч).
        /// </summary>
        public static string InvalidPublicKeyForCertificate {
            get {
                return ResourceManager.GetString("InvalidPublicKeyForCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вредноста за URL не е валидна.
        /// </summary>
        public static string InvalidUrlException {
            get {
                return ResourceManager.GetString("InvalidUrlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запис во пристапната листа со код за корисник &quot;{0}&quot; , код за провајдер &quot;{1}&quot; , и код за сервис &quot;{2}&quot; не постои во база.
        /// </summary>
        public static string NotFoundAccessMapping {
            get {
                return ResourceManager.GetString("NotFoundAccessMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientId &quot;{0}&quot; не е пронајден.
        /// </summary>
        public static string NotFoundClient {
            get {
                return ResourceManager.GetString("NotFoundClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е пронајден лог со трансакција &quot;{0}&quot;.
        /// </summary>
        public static string NotFoundMessageLog {
            get {
                return ResourceManager.GetString("NotFoundMessageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е пронајден лог со трансакциски код &quot;{0}&quot; и насока на комуникација &quot;{1}&quot;.
        /// </summary>
        public static string NotFoundMessageLogTransactionId {
            get {
                return ResourceManager.GetString("NotFoundMessageLogTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е пронајден учесник со код &quot;{0}&quot;.
        /// </summary>
        public static string NotFoundParticipant {
            get {
                return ResourceManager.GetString("NotFoundParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е пронајден јавен клуч за учесник со код &quot;{0}&quot;.
        /// </summary>
        public static string NotFoundPublicKeyException {
            get {
                return ResourceManager.GetString("NotFoundPublicKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е пронајден сервис со код за провајдер &quot;{0}&quot;, и код за сервис &quot;{1}&quot;.
        /// </summary>
        public static string NotFoundServiceException {
            get {
                return ResourceManager.GetString("NotFoundServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лозинките не се совпаѓаат.
        /// </summary>
        public static string PasswordDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лозинката мора да содржи најмалку 6 каракатери.
        /// </summary>
        public static string PasswordLengthSmall {
            get {
                return ResourceManager.GetString("PasswordLengthSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка при валидација на: &quot;{0}&quot;.
        /// </summary>
        public static string XmlValidation {
            get {
                return ResourceManager.GetString("XmlValidation", resourceCulture);
            }
        }
    }
}
