--GO

----MERGE generated by 'sp_generate_merge' stored procedure, Version 0.93
----Originally by Vyas (http://vyaskn.tripod.com): sp_generate_inserts (build 22)
----Adapted for SQL Server 2008/2012 by Daniel Nolan (http://danere.com)

--SET NOCOUNT ON

--MERGE INTO [SoapFault] AS Target
--USING (VALUES
--) AS Source ([TransactionId],[Code],[SubCode],[Reason],[Details],[DateOccured],[DateCreated])
--ON (Target.[TransactionId] = Source.[TransactionId])
--WHEN MATCHED AND (
--	NULLIF(Source.[Code], Target.[Code]) IS NOT NULL OR NULLIF(Target.[Code], Source.[Code]) IS NOT NULL OR 
--	NULLIF(Source.[SubCode], Target.[SubCode]) IS NOT NULL OR NULLIF(Target.[SubCode], Source.[SubCode]) IS NOT NULL OR 
--	NULLIF(Source.[Reason], Target.[Reason]) IS NOT NULL OR NULLIF(Target.[Reason], Source.[Reason]) IS NOT NULL OR 
--	NULLIF(Source.[Details], Target.[Details]) IS NOT NULL OR NULLIF(Target.[Details], Source.[Details]) IS NOT NULL OR 
--	NULLIF(Source.[DateOccured], Target.[DateOccured]) IS NOT NULL OR NULLIF(Target.[DateOccured], Source.[DateOccured]) IS NOT NULL OR 
--	NULLIF(Source.[DateCreated], Target.[DateCreated]) IS NOT NULL OR NULLIF(Target.[DateCreated], Source.[DateCreated]) IS NOT NULL) THEN
-- UPDATE SET
--  [Code] = Source.[Code], 
--  [SubCode] = Source.[SubCode], 
--  [Reason] = Source.[Reason], 
--  [Details] = Source.[Details], 
--  [DateOccured] = Source.[DateOccured], 
--  [DateCreated] = Source.[DateCreated]
--WHEN NOT MATCHED BY TARGET THEN
-- INSERT([TransactionId],[Code],[SubCode],[Reason],[Details],[DateOccured],[DateCreated])
-- VALUES(Source.[TransactionId],Source.[Code],Source.[SubCode],Source.[Reason],Source.[Details],Source.[DateOccured],Source.[DateCreated])
--WHEN NOT MATCHED BY SOURCE THEN 
-- DELETE;

--GO
--DECLARE @mergeError int
-- , @mergeCount int
--SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
--IF @mergeError != 0
-- BEGIN
-- PRINT 'ERROR OCCURRED IN MERGE FOR [SoapFault]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
-- END
--ELSE
-- BEGIN
-- PRINT '[SoapFault] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
-- END
--GO

--SET NOCOUNT OFF
--GO