//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAKNWebService.KopijaKatastarskiPlanDocument {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AKNDocOutput", Namespace="http://schemas.datacontract.org/2004/07/AdapterServiceAKN")]
    [System.SerializableAttribute()]
    public partial class AKNDocOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasDocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDocument {
            get {
                return this.HasDocumentField;
            }
            set {
                if ((this.HasDocumentField.Equals(value) != true)) {
                    this.HasDocumentField = value;
                    this.RaisePropertyChanged("HasDocument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interop.org/", ConfigurationName="KopijaKatastarskiPlanDocument.IAKNCPlanDoc")]
    public interface IAKNCPlanDoc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IAKNCPlanDoc/GetCPlanDoc", ReplyAction="http://interop.org/IAKNCPlanDoc/GetCPlanDocResponse")]
        TestAKNWebService.KopijaKatastarskiPlanDocument.AKNDocOutput GetCPlanDoc(string opstina, string katastarskaOpstina, string brImotenList, string brParcela, bool ShowEMB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IAKNCPlanDoc/GetCPlanDoc", ReplyAction="http://interop.org/IAKNCPlanDoc/GetCPlanDocResponse")]
        System.Threading.Tasks.Task<TestAKNWebService.KopijaKatastarskiPlanDocument.AKNDocOutput> GetCPlanDocAsync(string opstina, string katastarskaOpstina, string brImotenList, string brParcela, bool ShowEMB);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAKNCPlanDocChannel : TestAKNWebService.KopijaKatastarskiPlanDocument.IAKNCPlanDoc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AKNCPlanDocClient : System.ServiceModel.ClientBase<TestAKNWebService.KopijaKatastarskiPlanDocument.IAKNCPlanDoc>, TestAKNWebService.KopijaKatastarskiPlanDocument.IAKNCPlanDoc {
        
        public AKNCPlanDocClient() {
        }
        
        public AKNCPlanDocClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AKNCPlanDocClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AKNCPlanDocClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AKNCPlanDocClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestAKNWebService.KopijaKatastarskiPlanDocument.AKNDocOutput GetCPlanDoc(string opstina, string katastarskaOpstina, string brImotenList, string brParcela, bool ShowEMB) {
            return base.Channel.GetCPlanDoc(opstina, katastarskaOpstina, brImotenList, brParcela, ShowEMB);
        }
        
        public System.Threading.Tasks.Task<TestAKNWebService.KopijaKatastarskiPlanDocument.AKNDocOutput> GetCPlanDocAsync(string opstina, string katastarskaOpstina, string brImotenList, string brParcela, bool ShowEMB) {
            return base.Channel.GetCPlanDocAsync(opstina, katastarskaOpstina, brImotenList, brParcela, ShowEMB);
        }
    }
}
