//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DataExeExpProd {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutedExportInput", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DataAccessLibrary.DataForExecut" +
        "edExport")]
    [System.SerializableAttribute()]
    public partial class ExecutedExportInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AmountOfExportFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AmountOfExportToField;
        
        private long EDBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MonthOfExportFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MonthOfExportToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YearOfExportFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YearOfExportToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> AmountOfExportFrom {
            get {
                return this.AmountOfExportFromField;
            }
            set {
                if ((this.AmountOfExportFromField.Equals(value) != true)) {
                    this.AmountOfExportFromField = value;
                    this.RaisePropertyChanged("AmountOfExportFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> AmountOfExportTo {
            get {
                return this.AmountOfExportToField;
            }
            set {
                if ((this.AmountOfExportToField.Equals(value) != true)) {
                    this.AmountOfExportToField = value;
                    this.RaisePropertyChanged("AmountOfExportTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long EDB {
            get {
                return this.EDBField;
            }
            set {
                if ((this.EDBField.Equals(value) != true)) {
                    this.EDBField = value;
                    this.RaisePropertyChanged("EDB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MonthOfExportFrom {
            get {
                return this.MonthOfExportFromField;
            }
            set {
                if ((this.MonthOfExportFromField.Equals(value) != true)) {
                    this.MonthOfExportFromField = value;
                    this.RaisePropertyChanged("MonthOfExportFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MonthOfExportTo {
            get {
                return this.MonthOfExportToField;
            }
            set {
                if ((this.MonthOfExportToField.Equals(value) != true)) {
                    this.MonthOfExportToField = value;
                    this.RaisePropertyChanged("MonthOfExportTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YearOfExportFrom {
            get {
                return this.YearOfExportFromField;
            }
            set {
                if ((this.YearOfExportFromField.Equals(value) != true)) {
                    this.YearOfExportFromField = value;
                    this.RaisePropertyChanged("YearOfExportFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YearOfExportTo {
            get {
                return this.YearOfExportToField;
            }
            set {
                if ((this.YearOfExportToField.Equals(value) != true)) {
                    this.YearOfExportToField = value;
                    this.RaisePropertyChanged("YearOfExportTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutedExportOutput", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Models.DataForExecutedExport")]
    [System.SerializableAttribute()]
    public partial class ExecutedExportOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EDBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ExportAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExportMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExportYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EDB {
            get {
                return this.EDBField;
            }
            set {
                if ((object.ReferenceEquals(this.EDBField, value) != true)) {
                    this.EDBField = value;
                    this.RaisePropertyChanged("EDB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ExportAmount {
            get {
                return this.ExportAmountField;
            }
            set {
                if ((this.ExportAmountField.Equals(value) != true)) {
                    this.ExportAmountField = value;
                    this.RaisePropertyChanged("ExportAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExportMonth {
            get {
                return this.ExportMonthField;
            }
            set {
                if ((this.ExportMonthField.Equals(value) != true)) {
                    this.ExportMonthField = value;
                    this.RaisePropertyChanged("ExportMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExportYear {
            get {
                return this.ExportYearField;
            }
            set {
                if ((this.ExportYearField.Equals(value) != true)) {
                    this.ExportYearField = value;
                    this.RaisePropertyChanged("ExportYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InteropFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DataAccessLibrary")]
    [System.SerializableAttribute()]
    public partial class InteropFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interop.org/", ConfigurationName="DataExeExpProd.IDataExeExp")]
    public interface IDataExeExp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IDataExeExp/GetDataExeExp", ReplyAction="http://interop.org/IDataExeExp/GetDataExeExpResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestApp.DataExeExpProd.InteropFault), Action="http://interop.org/IDataExeExp/GetDataExeExpInteropFaultFault", Name="InteropFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DataAccessLibrary")]
        TestApp.DataExeExpProd.ExecutedExportOutput[] GetDataExeExp(TestApp.DataExeExpProd.ExecutedExportInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IDataExeExp/GetDataExeExp", ReplyAction="http://interop.org/IDataExeExp/GetDataExeExpResponse")]
        System.Threading.Tasks.Task<TestApp.DataExeExpProd.ExecutedExportOutput[]> GetDataExeExpAsync(TestApp.DataExeExpProd.ExecutedExportInput input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataExeExpChannel : TestApp.DataExeExpProd.IDataExeExp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataExeExpClient : System.ServiceModel.ClientBase<TestApp.DataExeExpProd.IDataExeExp>, TestApp.DataExeExpProd.IDataExeExp {
        
        public DataExeExpClient() {
        }
        
        public DataExeExpClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataExeExpClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataExeExpClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataExeExpClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestApp.DataExeExpProd.ExecutedExportOutput[] GetDataExeExp(TestApp.DataExeExpProd.ExecutedExportInput input) {
            return base.Channel.GetDataExeExp(input);
        }
        
        public System.Threading.Tasks.Task<TestApp.DataExeExpProd.ExecutedExportOutput[]> GetDataExeExpAsync(TestApp.DataExeExpProd.ExecutedExportInput input) {
            return base.Channel.GetDataExeExpAsync(input);
        }
    }
}
