//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAKNWebService.TSAdapterTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interop.org/", ConfigurationName="TSAdapterTest.ITSAdapterTest")]
    public interface ITSAdapterTest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ITSAdapterTest/GetTSTest", ReplyAction="http://interop.org/ITSAdapterTest/GetTSTestResponse")]
        string GetTSTest(string EMBS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ITSAdapterTest/GetTSTest", ReplyAction="http://interop.org/ITSAdapterTest/GetTSTestResponse")]
        System.Threading.Tasks.Task<string> GetTSTestAsync(string EMBS);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITSAdapterTestChannel : TestAKNWebService.TSAdapterTest.ITSAdapterTest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TSAdapterTestClient : System.ServiceModel.ClientBase<TestAKNWebService.TSAdapterTest.ITSAdapterTest>, TestAKNWebService.TSAdapterTest.ITSAdapterTest {
        
        public TSAdapterTestClient() {
        }
        
        public TSAdapterTestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TSAdapterTestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSAdapterTestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSAdapterTestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTSTest(string EMBS) {
            return base.Channel.GetTSTest(EMBS);
        }
        
        public System.Threading.Tasks.Task<string> GetTSTestAsync(string EMBS) {
            return base.Channel.GetTSTestAsync(EMBS);
        }
    }
}
