//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRRMTest.AdapterListOfChanges {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interop.org/", ConfigurationName="AdapterListOfChanges.IChanLstCU")]
    public interface IChanLstCU {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IChanLstCU/GetChangesCU", ReplyAction="http://interop.org/IChanLstCU/GetChangesCUResponse")]
        string GetChangesCU(string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IChanLstCU/GetChangesCU", ReplyAction="http://interop.org/IChanLstCU/GetChangesCUResponse")]
        System.Threading.Tasks.Task<string> GetChangesCUAsync(string param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChanLstCUChannel : CRRMTest.AdapterListOfChanges.IChanLstCU, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChanLstCUClient : System.ServiceModel.ClientBase<CRRMTest.AdapterListOfChanges.IChanLstCU>, CRRMTest.AdapterListOfChanges.IChanLstCU {
        
        public ChanLstCUClient() {
        }
        
        public ChanLstCUClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChanLstCUClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChanLstCUClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChanLstCUClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetChangesCU(string param) {
            return base.Channel.GetChangesCU(param);
        }
        
        public System.Threading.Tasks.Task<string> GetChangesCUAsync(string param) {
            return base.Channel.GetChangesCUAsync(param);
        }
    }
}
