//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAKNWebService.TSAdapterProduction {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interop.org/", ConfigurationName="TSAdapterProduction.ITSAdapterProduction")]
    public interface ITSAdapterProduction {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ITSAdapterProduction/GetTSProduction", ReplyAction="http://interop.org/ITSAdapterProduction/GetTSProductionResponse")]
        string GetTSProduction(string EMBS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ITSAdapterProduction/GetTSProduction", ReplyAction="http://interop.org/ITSAdapterProduction/GetTSProductionResponse")]
        System.Threading.Tasks.Task<string> GetTSProductionAsync(string EMBS);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITSAdapterProductionChannel : TestAKNWebService.TSAdapterProduction.ITSAdapterProduction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TSAdapterProductionClient : System.ServiceModel.ClientBase<TestAKNWebService.TSAdapterProduction.ITSAdapterProduction>, TestAKNWebService.TSAdapterProduction.ITSAdapterProduction {
        
        public TSAdapterProductionClient() {
        }
        
        public TSAdapterProductionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TSAdapterProductionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSAdapterProductionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSAdapterProductionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTSProduction(string EMBS) {
            return base.Channel.GetTSProduction(EMBS);
        }
        
        public System.Threading.Tasks.Task<string> GetTSProductionAsync(string EMBS) {
            return base.Channel.GetTSProductionAsync(EMBS);
        }
    }
}
