//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.RetiredStatus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interop.org/", ConfigurationName="RetiredStatus.IRetiredStatus")]
    public interface IRetiredStatus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IRetiredStatus/GetRetiredStatus", ReplyAction="http://interop.org/IRetiredStatus/GetRetiredStatusResponse")]
        string GetRetiredStatus(string embg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IRetiredStatus/GetRetiredStatus", ReplyAction="http://interop.org/IRetiredStatus/GetRetiredStatusResponse")]
        System.Threading.Tasks.Task<string> GetRetiredStatusAsync(string embg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRetiredStatusChannel : TestApp.RetiredStatus.IRetiredStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetiredStatusClient : System.ServiceModel.ClientBase<TestApp.RetiredStatus.IRetiredStatus>, TestApp.RetiredStatus.IRetiredStatus {
        
        public RetiredStatusClient() {
        }
        
        public RetiredStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetiredStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetiredStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetiredStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRetiredStatus(string embg) {
            return base.Channel.GetRetiredStatus(embg);
        }
        
        public System.Threading.Tasks.Task<string> GetRetiredStatusAsync(string embg) {
            return base.Channel.GetRetiredStatusAsync(embg);
        }
    }
}
