//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interop.CC.Portal.API.AKNKatastarskaParcela {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ATRparceli", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO_s.AKNService")]
    [System.SerializableAttribute()]
    public partial class ATRparceli : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Interop.CC.Portal.API.AKNKatastarskaParcela.ParcelAtr[] nizparField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Interop.CC.Portal.API.AKNKatastarskaParcela.ParcelAtr[] nizpar {
            get {
                return this.nizparField;
            }
            set {
                if ((object.ReferenceEquals(this.nizparField, value) != true)) {
                    this.nizparField = value;
                    this.RaisePropertyChanged("nizpar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParcelAtr", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO_s.AKNService")]
    [System.SerializableAttribute()]
    public partial class ParcelAtr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string broj_delField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ilistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kopsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kulturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int objektField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string opsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long povrsinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pravoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string broj_del {
            get {
                return this.broj_delField;
            }
            set {
                if ((object.ReferenceEquals(this.broj_delField, value) != true)) {
                    this.broj_delField = value;
                    this.RaisePropertyChanged("broj_del");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ilist {
            get {
                return this.ilistField;
            }
            set {
                if ((object.ReferenceEquals(this.ilistField, value) != true)) {
                    this.ilistField = value;
                    this.RaisePropertyChanged("ilist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kops {
            get {
                return this.kopsField;
            }
            set {
                if ((object.ReferenceEquals(this.kopsField, value) != true)) {
                    this.kopsField = value;
                    this.RaisePropertyChanged("kops");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kultura {
            get {
                return this.kulturaField;
            }
            set {
                if ((object.ReferenceEquals(this.kulturaField, value) != true)) {
                    this.kulturaField = value;
                    this.RaisePropertyChanged("kultura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mesto {
            get {
                return this.mestoField;
            }
            set {
                if ((object.ReferenceEquals(this.mestoField, value) != true)) {
                    this.mestoField = value;
                    this.RaisePropertyChanged("mesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int objekt {
            get {
                return this.objektField;
            }
            set {
                if ((this.objektField.Equals(value) != true)) {
                    this.objektField = value;
                    this.RaisePropertyChanged("objekt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ops {
            get {
                return this.opsField;
            }
            set {
                if ((object.ReferenceEquals(this.opsField, value) != true)) {
                    this.opsField = value;
                    this.RaisePropertyChanged("ops");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long povrsina {
            get {
                return this.povrsinaField;
            }
            set {
                if ((this.povrsinaField.Equals(value) != true)) {
                    this.povrsinaField = value;
                    this.RaisePropertyChanged("povrsina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pravo {
            get {
                return this.pravoField;
            }
            set {
                if ((object.ReferenceEquals(this.pravoField, value) != true)) {
                    this.pravoField = value;
                    this.RaisePropertyChanged("pravo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interop.org/", ConfigurationName="AKNKatastarskaParcela.ICadastrialParcel")]
    public interface ICadastrialParcel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ICadastrialParcel/GetCParcel", ReplyAction="http://interop.org/ICadastrialParcel/GetCParcelResponse")]
        Interop.CC.Portal.API.AKNKatastarskaParcela.ATRparceli GetCParcel(string username, string password, string opstina, string katastarskaOpstina, string brParcela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/ICadastrialParcel/GetCParcel", ReplyAction="http://interop.org/ICadastrialParcel/GetCParcelResponse")]
        System.Threading.Tasks.Task<Interop.CC.Portal.API.AKNKatastarskaParcela.ATRparceli> GetCParcelAsync(string username, string password, string opstina, string katastarskaOpstina, string brParcela);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICadastrialParcelChannel : Interop.CC.Portal.API.AKNKatastarskaParcela.ICadastrialParcel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CadastrialParcelClient : System.ServiceModel.ClientBase<Interop.CC.Portal.API.AKNKatastarskaParcela.ICadastrialParcel>, Interop.CC.Portal.API.AKNKatastarskaParcela.ICadastrialParcel {
        
        public CadastrialParcelClient() {
        }
        
        public CadastrialParcelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CadastrialParcelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CadastrialParcelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CadastrialParcelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Interop.CC.Portal.API.AKNKatastarskaParcela.ATRparceli GetCParcel(string username, string password, string opstina, string katastarskaOpstina, string brParcela) {
            return base.Channel.GetCParcel(username, password, opstina, katastarskaOpstina, brParcela);
        }
        
        public System.Threading.Tasks.Task<Interop.CC.Portal.API.AKNKatastarskaParcela.ATRparceli> GetCParcelAsync(string username, string password, string opstina, string katastarskaOpstina, string brParcela) {
            return base.Channel.GetCParcelAsync(username, password, opstina, katastarskaOpstina, brParcela);
        }
    }
}
