//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAKNWebService.RealAKNServiceForDocuments {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integracija.ekat.igea.si/", ConfigurationName="RealAKNServiceForDocuments.IntegracijaWSImpl")]
    public interface IntegracijaWSImpl {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/getTestResultRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/getTestResultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAKNWebService.RealAKNServiceForDocuments.getTestResultResponse getTestResult(TestAKNWebService.RealAKNServiceForDocuments.getTestResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/getTestResultRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/getTestResultResponse")]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.getTestResultResponse> getTestResultAsync(TestAKNWebService.RealAKNServiceForDocuments.getTestResultRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/printMessageRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/printMessageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAKNWebService.RealAKNServiceForDocuments.printMessageResponse printMessage(TestAKNWebService.RealAKNServiceForDocuments.printMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/printMessageRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/printMessageResponse")]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.printMessageResponse> printMessageAsync(TestAKNWebService.RealAKNServiceForDocuments.printMessageRequest request);
        
        // CODEGEN: Parameter 'SifUpo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/insOISDUserRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/insOISDUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SifUpo")]
        TestAKNWebService.RealAKNServiceForDocuments.insOISDUserResponse insOISDUser(TestAKNWebService.RealAKNServiceForDocuments.insOISDUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/insOISDUserRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/insOISDUserResponse")]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.insOISDUserResponse> insOISDUserAsync(TestAKNWebService.RealAKNServiceForDocuments.insOISDUserRequest request);
        
        // CODEGEN: Parameter 'IdPtype' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/insNewProcedureRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/insNewProcedureResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IdPtype")]
        TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureResponse insNewProcedure(TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/insNewProcedureRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/insNewProcedureResponse")]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureResponse> insNewProcedureAsync(TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureRequest request);
        
        // CODEGEN: Parameter 'SifUpo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/insLiteUserRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/insLiteUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SifUpo")]
        TestAKNWebService.RealAKNServiceForDocuments.insLiteUserResponse insLiteUser(TestAKNWebService.RealAKNServiceForDocuments.insLiteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/insLiteUserRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/insLiteUserResponse")]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.insLiteUserResponse> insLiteUserAsync(TestAKNWebService.RealAKNServiceForDocuments.insLiteUserRequest request);
        
        // CODEGEN: Parameter 'PayedReqs' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/getPayedReqRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/getPayedReqResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PayedReqs")]
        TestAKNWebService.RealAKNServiceForDocuments.getPayedReqResponse getPayedReq(TestAKNWebService.RealAKNServiceForDocuments.getPayedReqRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/getPayedReqRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/getPayedReqResponse")]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.getPayedReqResponse> getPayedReqAsync(TestAKNWebService.RealAKNServiceForDocuments.getPayedReqRequest request);
        
        // CODEGEN: Parameter 'PlistInfo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/getPlistInfoRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/getPlistInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PlistInfo")]
        TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoResponse getPlistInfo(TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/getPlistInfoRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/getPlistInfoResponse")]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoResponse> getPlistInfoAsync(TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoRequest request);
        
        // CODEGEN: Parameter 'GenerateDocument' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/generateDocumentRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/generateDocumentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GenerateDocument")]
        TestAKNWebService.RealAKNServiceForDocuments.generateDocumentResponse generateDocument(TestAKNWebService.RealAKNServiceForDocuments.generateDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracija.ekat.igea.si/IntegracijaWSImpl/generateDocumentRequest", ReplyAction="http://integracija.ekat.igea.si/IntegracijaWSImpl/generateDocumentResponse")]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.generateDocumentResponse> generateDocumentAsync(TestAKNWebService.RealAKNServiceForDocuments.generateDocumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTestResult", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class getTestResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getTestResultRequest() {
        }
        
        public getTestResultRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTestResultResponse", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class getTestResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getTestResultResponse() {
        }
        
        public getTestResultResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="printMessage", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class printMessageRequest {
        
        public printMessageRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="printMessageResponse", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class printMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public printMessageResponse() {
        }
        
        public printMessageResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insOISDUser", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class insOISDUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int IdErp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastName;
        
        public insOISDUserRequest() {
        }
        
        public insOISDUserRequest(int IdErp, string FirstName, string LastName) {
            this.IdErp = IdErp;
            this.FirstName = FirstName;
            this.LastName = LastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insOISDUserResponse", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class insOISDUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SifUpo;
        
        public insOISDUserResponse() {
        }
        
        public insOISDUserResponse(decimal SifUpo) {
            this.SifUpo = SifUpo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insNewProcedure", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class insNewProcedureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Price;
        
        public insNewProcedureRequest() {
        }
        
        public insNewProcedureRequest(int Id, string Name, decimal Price) {
            this.Id = Id;
            this.Name = Name;
            this.Price = Price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insNewProcedureResponse", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class insNewProcedureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal IdPtype;
        
        public insNewProcedureResponse() {
        }
        
        public insNewProcedureResponse(decimal IdPtype) {
            this.IdPtype = IdPtype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insLiteUser", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class insLiteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int IdErp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TaxNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ZIP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Telephone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eMail;
        
        public insLiteUserRequest() {
        }
        
        public insLiteUserRequest(int IdErp, string FirstName, string LastName, int TaxNumber, string Address, string City, int ZIP, string Telephone, string eMail) {
            this.IdErp = IdErp;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.TaxNumber = TaxNumber;
            this.Address = Address;
            this.City = City;
            this.ZIP = ZIP;
            this.Telephone = Telephone;
            this.eMail = eMail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insLiteUserResponse", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class insLiteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SifUpo;
        
        public insLiteUserResponse() {
        }
        
        public insLiteUserResponse(decimal SifUpo) {
            this.SifUpo = SifUpo;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integracija.ekat.igea.si/")]
    public partial class payedReq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amountSumField;
        
        private string arhSignField;
        
        private int codDpField;
        
        private bool codDpFieldSpecified;
        
        private string endedDateField;
        
        private string reqArhnumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string amountSum {
            get {
                return this.amountSumField;
            }
            set {
                this.amountSumField = value;
                this.RaisePropertyChanged("amountSum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arhSign {
            get {
                return this.arhSignField;
            }
            set {
                this.arhSignField = value;
                this.RaisePropertyChanged("arhSign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codDp {
            get {
                return this.codDpField;
            }
            set {
                this.codDpField = value;
                this.RaisePropertyChanged("codDp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codDpSpecified {
            get {
                return this.codDpFieldSpecified;
            }
            set {
                this.codDpFieldSpecified = value;
                this.RaisePropertyChanged("codDpSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string endedDate {
            get {
                return this.endedDateField;
            }
            set {
                this.endedDateField = value;
                this.RaisePropertyChanged("endedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string reqArhnumber {
            get {
                return this.reqArhnumberField;
            }
            set {
                this.reqArhnumberField = value;
                this.RaisePropertyChanged("reqArhnumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integracija.ekat.igea.si/")]
    public partial class documentInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string baseURLField;
        
        private string erridField;
        
        private string errmsgField;
        
        private string fileNameField;
        
        private string filePathField;
        
        private string fileURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string baseURL {
            get {
                return this.baseURLField;
            }
            set {
                this.baseURLField = value;
                this.RaisePropertyChanged("baseURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errid {
            get {
                return this.erridField;
            }
            set {
                this.erridField = value;
                this.RaisePropertyChanged("errid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errmsg {
            get {
                return this.errmsgField;
            }
            set {
                this.errmsgField = value;
                this.RaisePropertyChanged("errmsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string filePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
                this.RaisePropertyChanged("filePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fileURL {
            get {
                return this.fileURLField;
            }
            set {
                this.fileURLField = value;
                this.RaisePropertyChanged("fileURL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integracija.ekat.igea.si/")]
    public partial class plistInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erridField;
        
        private string errmsgField;
        
        private string idPtypeField;
        
        private string infoField;
        
        private string priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errid {
            get {
                return this.erridField;
            }
            set {
                this.erridField = value;
                this.RaisePropertyChanged("errid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errmsg {
            get {
                return this.errmsgField;
            }
            set {
                this.errmsgField = value;
                this.RaisePropertyChanged("errmsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string idPtype {
            get {
                return this.idPtypeField;
            }
            set {
                this.idPtypeField = value;
                this.RaisePropertyChanged("idPtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPayedReq", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class getPayedReqRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateTo;
        
        public getPayedReqRequest() {
        }
        
        public getPayedReqRequest(string DateFrom, string DateTo) {
            this.DateFrom = DateFrom;
            this.DateTo = DateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPayedReqResponse", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class getPayedReqResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("payedReqs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAKNWebService.RealAKNServiceForDocuments.payedReq[] PayedReqs;
        
        public getPayedReqResponse() {
        }
        
        public getPayedReqResponse(TestAKNWebService.RealAKNServiceForDocuments.payedReq[] PayedReqs) {
            this.PayedReqs = PayedReqs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPlistInfo", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class getPlistInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodDP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodCC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdPlist;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Parcel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UcadStatus;
        
        public getPlistInfoRequest() {
        }
        
        public getPlistInfoRequest(string CodDP, string CodCC, string IdPlist, string Parcel, string UcadStatus) {
            this.CodDP = CodDP;
            this.CodCC = CodCC;
            this.IdPlist = IdPlist;
            this.Parcel = Parcel;
            this.UcadStatus = UcadStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPlistInfoResponse", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class getPlistInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAKNWebService.RealAKNServiceForDocuments.plistInfo PlistInfo;
        
        public getPlistInfoResponse() {
        }
        
        public getPlistInfoResponse(TestAKNWebService.RealAKNServiceForDocuments.plistInfo PlistInfo) {
            this.PlistInfo = PlistInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateDocument", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class generateDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodDP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodCC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdPlist;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Parcel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMBGStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdPtype;
        
        public generateDocumentRequest() {
        }
        
        public generateDocumentRequest(string CodDP, string CodCC, string IdPlist, string Parcel, string EMBGStatus, string IdPtype) {
            this.CodDP = CodDP;
            this.CodCC = CodCC;
            this.IdPlist = IdPlist;
            this.Parcel = Parcel;
            this.EMBGStatus = EMBGStatus;
            this.IdPtype = IdPtype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateDocumentResponse", WrapperNamespace="http://integracija.ekat.igea.si/", IsWrapped=true)]
    public partial class generateDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracija.ekat.igea.si/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAKNWebService.RealAKNServiceForDocuments.documentInfo GenerateDocument;
        
        public generateDocumentResponse() {
        }
        
        public generateDocumentResponse(TestAKNWebService.RealAKNServiceForDocuments.documentInfo GenerateDocument) {
            this.GenerateDocument = GenerateDocument;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntegracijaWSImplChannel : TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegracijaWSImplClient : System.ServiceModel.ClientBase<TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl>, TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl {
        
        public IntegracijaWSImplClient() {
        }
        
        public IntegracijaWSImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegracijaWSImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracijaWSImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracijaWSImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAKNWebService.RealAKNServiceForDocuments.getTestResultResponse TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.getTestResult(TestAKNWebService.RealAKNServiceForDocuments.getTestResultRequest request) {
            return base.Channel.getTestResult(request);
        }
        
        public string getTestResult(string arg0) {
            TestAKNWebService.RealAKNServiceForDocuments.getTestResultRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.getTestResultRequest();
            inValue.arg0 = arg0;
            TestAKNWebService.RealAKNServiceForDocuments.getTestResultResponse retVal = ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).getTestResult(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.getTestResultResponse> TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.getTestResultAsync(TestAKNWebService.RealAKNServiceForDocuments.getTestResultRequest request) {
            return base.Channel.getTestResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.getTestResultResponse> getTestResultAsync(string arg0) {
            TestAKNWebService.RealAKNServiceForDocuments.getTestResultRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.getTestResultRequest();
            inValue.arg0 = arg0;
            return ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).getTestResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAKNWebService.RealAKNServiceForDocuments.printMessageResponse TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.printMessage(TestAKNWebService.RealAKNServiceForDocuments.printMessageRequest request) {
            return base.Channel.printMessage(request);
        }
        
        public string printMessage() {
            TestAKNWebService.RealAKNServiceForDocuments.printMessageRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.printMessageRequest();
            TestAKNWebService.RealAKNServiceForDocuments.printMessageResponse retVal = ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).printMessage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.printMessageResponse> TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.printMessageAsync(TestAKNWebService.RealAKNServiceForDocuments.printMessageRequest request) {
            return base.Channel.printMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.printMessageResponse> printMessageAsync() {
            TestAKNWebService.RealAKNServiceForDocuments.printMessageRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.printMessageRequest();
            return ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).printMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAKNWebService.RealAKNServiceForDocuments.insOISDUserResponse TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.insOISDUser(TestAKNWebService.RealAKNServiceForDocuments.insOISDUserRequest request) {
            return base.Channel.insOISDUser(request);
        }
        
        public decimal insOISDUser(int IdErp, string FirstName, string LastName) {
            TestAKNWebService.RealAKNServiceForDocuments.insOISDUserRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.insOISDUserRequest();
            inValue.IdErp = IdErp;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            TestAKNWebService.RealAKNServiceForDocuments.insOISDUserResponse retVal = ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).insOISDUser(inValue);
            return retVal.SifUpo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.insOISDUserResponse> TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.insOISDUserAsync(TestAKNWebService.RealAKNServiceForDocuments.insOISDUserRequest request) {
            return base.Channel.insOISDUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.insOISDUserResponse> insOISDUserAsync(int IdErp, string FirstName, string LastName) {
            TestAKNWebService.RealAKNServiceForDocuments.insOISDUserRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.insOISDUserRequest();
            inValue.IdErp = IdErp;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            return ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).insOISDUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureResponse TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.insNewProcedure(TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureRequest request) {
            return base.Channel.insNewProcedure(request);
        }
        
        public decimal insNewProcedure(int Id, string Name, decimal Price) {
            TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureRequest();
            inValue.Id = Id;
            inValue.Name = Name;
            inValue.Price = Price;
            TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureResponse retVal = ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).insNewProcedure(inValue);
            return retVal.IdPtype;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureResponse> TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.insNewProcedureAsync(TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureRequest request) {
            return base.Channel.insNewProcedureAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureResponse> insNewProcedureAsync(int Id, string Name, decimal Price) {
            TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.insNewProcedureRequest();
            inValue.Id = Id;
            inValue.Name = Name;
            inValue.Price = Price;
            return ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).insNewProcedureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAKNWebService.RealAKNServiceForDocuments.insLiteUserResponse TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.insLiteUser(TestAKNWebService.RealAKNServiceForDocuments.insLiteUserRequest request) {
            return base.Channel.insLiteUser(request);
        }
        
        public decimal insLiteUser(int IdErp, string FirstName, string LastName, int TaxNumber, string Address, string City, int ZIP, string Telephone, string eMail) {
            TestAKNWebService.RealAKNServiceForDocuments.insLiteUserRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.insLiteUserRequest();
            inValue.IdErp = IdErp;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.TaxNumber = TaxNumber;
            inValue.Address = Address;
            inValue.City = City;
            inValue.ZIP = ZIP;
            inValue.Telephone = Telephone;
            inValue.eMail = eMail;
            TestAKNWebService.RealAKNServiceForDocuments.insLiteUserResponse retVal = ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).insLiteUser(inValue);
            return retVal.SifUpo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.insLiteUserResponse> TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.insLiteUserAsync(TestAKNWebService.RealAKNServiceForDocuments.insLiteUserRequest request) {
            return base.Channel.insLiteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.insLiteUserResponse> insLiteUserAsync(int IdErp, string FirstName, string LastName, int TaxNumber, string Address, string City, int ZIP, string Telephone, string eMail) {
            TestAKNWebService.RealAKNServiceForDocuments.insLiteUserRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.insLiteUserRequest();
            inValue.IdErp = IdErp;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.TaxNumber = TaxNumber;
            inValue.Address = Address;
            inValue.City = City;
            inValue.ZIP = ZIP;
            inValue.Telephone = Telephone;
            inValue.eMail = eMail;
            return ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).insLiteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAKNWebService.RealAKNServiceForDocuments.getPayedReqResponse TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.getPayedReq(TestAKNWebService.RealAKNServiceForDocuments.getPayedReqRequest request) {
            return base.Channel.getPayedReq(request);
        }
        
        public TestAKNWebService.RealAKNServiceForDocuments.payedReq[] getPayedReq(string DateFrom, string DateTo) {
            TestAKNWebService.RealAKNServiceForDocuments.getPayedReqRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.getPayedReqRequest();
            inValue.DateFrom = DateFrom;
            inValue.DateTo = DateTo;
            TestAKNWebService.RealAKNServiceForDocuments.getPayedReqResponse retVal = ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).getPayedReq(inValue);
            return retVal.PayedReqs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.getPayedReqResponse> TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.getPayedReqAsync(TestAKNWebService.RealAKNServiceForDocuments.getPayedReqRequest request) {
            return base.Channel.getPayedReqAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.getPayedReqResponse> getPayedReqAsync(string DateFrom, string DateTo) {
            TestAKNWebService.RealAKNServiceForDocuments.getPayedReqRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.getPayedReqRequest();
            inValue.DateFrom = DateFrom;
            inValue.DateTo = DateTo;
            return ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).getPayedReqAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoResponse TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.getPlistInfo(TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoRequest request) {
            return base.Channel.getPlistInfo(request);
        }
        
        public TestAKNWebService.RealAKNServiceForDocuments.plistInfo getPlistInfo(string CodDP, string CodCC, string IdPlist, string Parcel, string UcadStatus) {
            TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoRequest();
            inValue.CodDP = CodDP;
            inValue.CodCC = CodCC;
            inValue.IdPlist = IdPlist;
            inValue.Parcel = Parcel;
            inValue.UcadStatus = UcadStatus;
            TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoResponse retVal = ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).getPlistInfo(inValue);
            return retVal.PlistInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoResponse> TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.getPlistInfoAsync(TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoRequest request) {
            return base.Channel.getPlistInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoResponse> getPlistInfoAsync(string CodDP, string CodCC, string IdPlist, string Parcel, string UcadStatus) {
            TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.getPlistInfoRequest();
            inValue.CodDP = CodDP;
            inValue.CodCC = CodCC;
            inValue.IdPlist = IdPlist;
            inValue.Parcel = Parcel;
            inValue.UcadStatus = UcadStatus;
            return ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).getPlistInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAKNWebService.RealAKNServiceForDocuments.generateDocumentResponse TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.generateDocument(TestAKNWebService.RealAKNServiceForDocuments.generateDocumentRequest request) {
            return base.Channel.generateDocument(request);
        }
        
        public TestAKNWebService.RealAKNServiceForDocuments.documentInfo generateDocument(string CodDP, string CodCC, string IdPlist, string Parcel, string EMBGStatus, string IdPtype) {
            TestAKNWebService.RealAKNServiceForDocuments.generateDocumentRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.generateDocumentRequest();
            inValue.CodDP = CodDP;
            inValue.CodCC = CodCC;
            inValue.IdPlist = IdPlist;
            inValue.Parcel = Parcel;
            inValue.EMBGStatus = EMBGStatus;
            inValue.IdPtype = IdPtype;
            TestAKNWebService.RealAKNServiceForDocuments.generateDocumentResponse retVal = ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).generateDocument(inValue);
            return retVal.GenerateDocument;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.generateDocumentResponse> TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl.generateDocumentAsync(TestAKNWebService.RealAKNServiceForDocuments.generateDocumentRequest request) {
            return base.Channel.generateDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAKNWebService.RealAKNServiceForDocuments.generateDocumentResponse> generateDocumentAsync(string CodDP, string CodCC, string IdPlist, string Parcel, string EMBGStatus, string IdPtype) {
            TestAKNWebService.RealAKNServiceForDocuments.generateDocumentRequest inValue = new TestAKNWebService.RealAKNServiceForDocuments.generateDocumentRequest();
            inValue.CodDP = CodDP;
            inValue.CodCC = CodCC;
            inValue.IdPlist = IdPlist;
            inValue.Parcel = Parcel;
            inValue.EMBGStatus = EMBGStatus;
            inValue.IdPtype = IdPtype;
            return ((TestAKNWebService.RealAKNServiceForDocuments.IntegracijaWSImpl)(this)).generateDocumentAsync(inValue);
        }
    }
}
