//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interop.CC.Portal.API.UJPDataForAnnualRevenues {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnnualRevenuesMTSPOutput", Namespace="http://schemas.datacontract.org/2004/07/InteropServices.UJP.Implementations")]
    [System.SerializableAttribute()]
    public partial class AnnualRevenuesMTSPOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EDBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Licniprim_BrutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Licniprim_NetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Plata_3m_BrutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Plata_3m_NetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_AvtorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_DrugoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_IgriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_ImotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_KapdobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_KapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_SvdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_ZemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZabeleskaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EDB {
            get {
                return this.EDBField;
            }
            set {
                if ((object.ReferenceEquals(this.EDBField, value) != true)) {
                    this.EDBField = value;
                    this.RaisePropertyChanged("EDB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Licniprim_Bruto {
            get {
                return this.Licniprim_BrutoField;
            }
            set {
                if ((object.ReferenceEquals(this.Licniprim_BrutoField, value) != true)) {
                    this.Licniprim_BrutoField = value;
                    this.RaisePropertyChanged("Licniprim_Bruto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Licniprim_Neto {
            get {
                return this.Licniprim_NetoField;
            }
            set {
                if ((object.ReferenceEquals(this.Licniprim_NetoField, value) != true)) {
                    this.Licniprim_NetoField = value;
                    this.RaisePropertyChanged("Licniprim_Neto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plata_3m_Bruto {
            get {
                return this.Plata_3m_BrutoField;
            }
            set {
                if ((object.ReferenceEquals(this.Plata_3m_BrutoField, value) != true)) {
                    this.Plata_3m_BrutoField = value;
                    this.RaisePropertyChanged("Plata_3m_Bruto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plata_3m_Neto {
            get {
                return this.Plata_3m_NetoField;
            }
            set {
                if ((object.ReferenceEquals(this.Plata_3m_NetoField, value) != true)) {
                    this.Plata_3m_NetoField = value;
                    this.RaisePropertyChanged("Plata_3m_Neto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Avtor {
            get {
                return this.Prihodi_AvtorField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_AvtorField, value) != true)) {
                    this.Prihodi_AvtorField = value;
                    this.RaisePropertyChanged("Prihodi_Avtor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Drugo {
            get {
                return this.Prihodi_DrugoField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_DrugoField, value) != true)) {
                    this.Prihodi_DrugoField = value;
                    this.RaisePropertyChanged("Prihodi_Drugo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Igri {
            get {
                return this.Prihodi_IgriField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_IgriField, value) != true)) {
                    this.Prihodi_IgriField = value;
                    this.RaisePropertyChanged("Prihodi_Igri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Imot {
            get {
                return this.Prihodi_ImotField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_ImotField, value) != true)) {
                    this.Prihodi_ImotField = value;
                    this.RaisePropertyChanged("Prihodi_Imot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Kapdob {
            get {
                return this.Prihodi_KapdobField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_KapdobField, value) != true)) {
                    this.Prihodi_KapdobField = value;
                    this.RaisePropertyChanged("Prihodi_Kapdob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Kapital {
            get {
                return this.Prihodi_KapitalField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_KapitalField, value) != true)) {
                    this.Prihodi_KapitalField = value;
                    this.RaisePropertyChanged("Prihodi_Kapital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Svd {
            get {
                return this.Prihodi_SvdField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_SvdField, value) != true)) {
                    this.Prihodi_SvdField = value;
                    this.RaisePropertyChanged("Prihodi_Svd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Zem {
            get {
                return this.Prihodi_ZemField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_ZemField, value) != true)) {
                    this.Prihodi_ZemField = value;
                    this.RaisePropertyChanged("Prihodi_Zem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zabeleska {
            get {
                return this.ZabeleskaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZabeleskaField, value) != true)) {
                    this.ZabeleskaField = value;
                    this.RaisePropertyChanged("Zabeleska");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnnualRevenuesMONOutput", Namespace="http://schemas.datacontract.org/2004/07/InteropServices.UJP.Implementations")]
    [System.SerializableAttribute()]
    public partial class AnnualRevenuesMONOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EDBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Licniprim_BrutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Licniprim_NetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_AvtorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_DrugoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_IgriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_ImotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_KapdobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_KapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_SvdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prihodi_ZemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZabeleskaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EDB {
            get {
                return this.EDBField;
            }
            set {
                if ((object.ReferenceEquals(this.EDBField, value) != true)) {
                    this.EDBField = value;
                    this.RaisePropertyChanged("EDB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Licniprim_Bruto {
            get {
                return this.Licniprim_BrutoField;
            }
            set {
                if ((object.ReferenceEquals(this.Licniprim_BrutoField, value) != true)) {
                    this.Licniprim_BrutoField = value;
                    this.RaisePropertyChanged("Licniprim_Bruto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Licniprim_Neto {
            get {
                return this.Licniprim_NetoField;
            }
            set {
                if ((object.ReferenceEquals(this.Licniprim_NetoField, value) != true)) {
                    this.Licniprim_NetoField = value;
                    this.RaisePropertyChanged("Licniprim_Neto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Avtor {
            get {
                return this.Prihodi_AvtorField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_AvtorField, value) != true)) {
                    this.Prihodi_AvtorField = value;
                    this.RaisePropertyChanged("Prihodi_Avtor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Drugo {
            get {
                return this.Prihodi_DrugoField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_DrugoField, value) != true)) {
                    this.Prihodi_DrugoField = value;
                    this.RaisePropertyChanged("Prihodi_Drugo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Igri {
            get {
                return this.Prihodi_IgriField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_IgriField, value) != true)) {
                    this.Prihodi_IgriField = value;
                    this.RaisePropertyChanged("Prihodi_Igri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Imot {
            get {
                return this.Prihodi_ImotField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_ImotField, value) != true)) {
                    this.Prihodi_ImotField = value;
                    this.RaisePropertyChanged("Prihodi_Imot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Kapdob {
            get {
                return this.Prihodi_KapdobField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_KapdobField, value) != true)) {
                    this.Prihodi_KapdobField = value;
                    this.RaisePropertyChanged("Prihodi_Kapdob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Kapital {
            get {
                return this.Prihodi_KapitalField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_KapitalField, value) != true)) {
                    this.Prihodi_KapitalField = value;
                    this.RaisePropertyChanged("Prihodi_Kapital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Svd {
            get {
                return this.Prihodi_SvdField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_SvdField, value) != true)) {
                    this.Prihodi_SvdField = value;
                    this.RaisePropertyChanged("Prihodi_Svd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prihodi_Zem {
            get {
                return this.Prihodi_ZemField;
            }
            set {
                if ((object.ReferenceEquals(this.Prihodi_ZemField, value) != true)) {
                    this.Prihodi_ZemField = value;
                    this.RaisePropertyChanged("Prihodi_Zem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zabeleska {
            get {
                return this.ZabeleskaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZabeleskaField, value) != true)) {
                    this.ZabeleskaField = value;
                    this.RaisePropertyChanged("Zabeleska");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnnualRevenuesFZOOutput", Namespace="http://schemas.datacontract.org/2004/07/InteropServices.UJP.Implementations")]
    [System.SerializableAttribute()]
    public partial class AnnualRevenuesFZOOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EDBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FZO_BrutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FZO_NetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZabeleskaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EDB {
            get {
                return this.EDBField;
            }
            set {
                if ((object.ReferenceEquals(this.EDBField, value) != true)) {
                    this.EDBField = value;
                    this.RaisePropertyChanged("EDB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FZO_Bruto {
            get {
                return this.FZO_BrutoField;
            }
            set {
                if ((object.ReferenceEquals(this.FZO_BrutoField, value) != true)) {
                    this.FZO_BrutoField = value;
                    this.RaisePropertyChanged("FZO_Bruto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FZO_Neto {
            get {
                return this.FZO_NetoField;
            }
            set {
                if ((object.ReferenceEquals(this.FZO_NetoField, value) != true)) {
                    this.FZO_NetoField = value;
                    this.RaisePropertyChanged("FZO_Neto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zabeleska {
            get {
                return this.ZabeleskaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZabeleskaField, value) != true)) {
                    this.ZabeleskaField = value;
                    this.RaisePropertyChanged("Zabeleska");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnnualRevenuesKKKSOutput", Namespace="http://schemas.datacontract.org/2004/07/InteropServices.UJP.Implementations")]
    [System.SerializableAttribute()]
    public partial class AnnualRevenuesKKKSOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Drugo_BrutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Drugo_NetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EDBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mes6_BrojField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mes6_BrutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mes6_NetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pospl_BrutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pospl_NetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pospl_mmggField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vk_BrutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vk_NetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZabeleskaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Drugo_Bruto {
            get {
                return this.Drugo_BrutoField;
            }
            set {
                if ((object.ReferenceEquals(this.Drugo_BrutoField, value) != true)) {
                    this.Drugo_BrutoField = value;
                    this.RaisePropertyChanged("Drugo_Bruto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Drugo_Neto {
            get {
                return this.Drugo_NetoField;
            }
            set {
                if ((object.ReferenceEquals(this.Drugo_NetoField, value) != true)) {
                    this.Drugo_NetoField = value;
                    this.RaisePropertyChanged("Drugo_Neto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EDB {
            get {
                return this.EDBField;
            }
            set {
                if ((object.ReferenceEquals(this.EDBField, value) != true)) {
                    this.EDBField = value;
                    this.RaisePropertyChanged("EDB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mes6_Broj {
            get {
                return this.Mes6_BrojField;
            }
            set {
                if ((object.ReferenceEquals(this.Mes6_BrojField, value) != true)) {
                    this.Mes6_BrojField = value;
                    this.RaisePropertyChanged("Mes6_Broj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mes6_Bruto {
            get {
                return this.Mes6_BrutoField;
            }
            set {
                if ((object.ReferenceEquals(this.Mes6_BrutoField, value) != true)) {
                    this.Mes6_BrutoField = value;
                    this.RaisePropertyChanged("Mes6_Bruto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mes6_Neto {
            get {
                return this.Mes6_NetoField;
            }
            set {
                if ((object.ReferenceEquals(this.Mes6_NetoField, value) != true)) {
                    this.Mes6_NetoField = value;
                    this.RaisePropertyChanged("Mes6_Neto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pospl_Bruto {
            get {
                return this.Pospl_BrutoField;
            }
            set {
                if ((object.ReferenceEquals(this.Pospl_BrutoField, value) != true)) {
                    this.Pospl_BrutoField = value;
                    this.RaisePropertyChanged("Pospl_Bruto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pospl_Neto {
            get {
                return this.Pospl_NetoField;
            }
            set {
                if ((object.ReferenceEquals(this.Pospl_NetoField, value) != true)) {
                    this.Pospl_NetoField = value;
                    this.RaisePropertyChanged("Pospl_Neto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pospl_mmgg {
            get {
                return this.Pospl_mmggField;
            }
            set {
                if ((object.ReferenceEquals(this.Pospl_mmggField, value) != true)) {
                    this.Pospl_mmggField = value;
                    this.RaisePropertyChanged("Pospl_mmgg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vk_Bruto {
            get {
                return this.Vk_BrutoField;
            }
            set {
                if ((object.ReferenceEquals(this.Vk_BrutoField, value) != true)) {
                    this.Vk_BrutoField = value;
                    this.RaisePropertyChanged("Vk_Bruto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vk_Neto {
            get {
                return this.Vk_NetoField;
            }
            set {
                if ((object.ReferenceEquals(this.Vk_NetoField, value) != true)) {
                    this.Vk_NetoField = value;
                    this.RaisePropertyChanged("Vk_Neto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zabeleska {
            get {
                return this.ZabeleskaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZabeleskaField, value) != true)) {
                    this.ZabeleskaField = value;
                    this.RaisePropertyChanged("Zabeleska");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interop.org", ConfigurationName="UJPDataForAnnualRevenues.IDataAnnRev")]
    public interface IDataAnnRev {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IDataAnnRev/GetAnnualRevenuesMTSP", ReplyAction="http://interop.org/IDataAnnRev/GetAnnualRevenuesMTSPResponse")]
        Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesMTSPOutput GetAnnualRevenuesMTSP(string EDB, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IDataAnnRev/GetAnnualRevenuesMTSP", ReplyAction="http://interop.org/IDataAnnRev/GetAnnualRevenuesMTSPResponse")]
        System.Threading.Tasks.Task<Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesMTSPOutput> GetAnnualRevenuesMTSPAsync(string EDB, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IDataAnnRev/GetAnnualRevenuesMON", ReplyAction="http://interop.org/IDataAnnRev/GetAnnualRevenuesMONResponse")]
        Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesMONOutput GetAnnualRevenuesMON(string EDB, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IDataAnnRev/GetAnnualRevenuesMON", ReplyAction="http://interop.org/IDataAnnRev/GetAnnualRevenuesMONResponse")]
        System.Threading.Tasks.Task<Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesMONOutput> GetAnnualRevenuesMONAsync(string EDB, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IDataAnnRev/GetAnnualRevenuesFZO", ReplyAction="http://interop.org/IDataAnnRev/GetAnnualRevenuesFZOResponse")]
        Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesFZOOutput GetAnnualRevenuesFZO(string EDB, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IDataAnnRev/GetAnnualRevenuesFZO", ReplyAction="http://interop.org/IDataAnnRev/GetAnnualRevenuesFZOResponse")]
        System.Threading.Tasks.Task<Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesFZOOutput> GetAnnualRevenuesFZOAsync(string EDB, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IDataAnnRev/GetAnnualRevenuesKKKS", ReplyAction="http://interop.org/IDataAnnRev/GetAnnualRevenuesKKKSResponse")]
        Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesKKKSOutput GetAnnualRevenuesKKKS(string EDB, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interop.org/IDataAnnRev/GetAnnualRevenuesKKKS", ReplyAction="http://interop.org/IDataAnnRev/GetAnnualRevenuesKKKSResponse")]
        System.Threading.Tasks.Task<Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesKKKSOutput> GetAnnualRevenuesKKKSAsync(string EDB, string year);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataAnnRevChannel : Interop.CC.Portal.API.UJPDataForAnnualRevenues.IDataAnnRev, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataAnnRevClient : System.ServiceModel.ClientBase<Interop.CC.Portal.API.UJPDataForAnnualRevenues.IDataAnnRev>, Interop.CC.Portal.API.UJPDataForAnnualRevenues.IDataAnnRev {
        
        public DataAnnRevClient() {
        }
        
        public DataAnnRevClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataAnnRevClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataAnnRevClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataAnnRevClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesMTSPOutput GetAnnualRevenuesMTSP(string EDB, string year) {
            return base.Channel.GetAnnualRevenuesMTSP(EDB, year);
        }
        
        public System.Threading.Tasks.Task<Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesMTSPOutput> GetAnnualRevenuesMTSPAsync(string EDB, string year) {
            return base.Channel.GetAnnualRevenuesMTSPAsync(EDB, year);
        }
        
        public Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesMONOutput GetAnnualRevenuesMON(string EDB, string year) {
            return base.Channel.GetAnnualRevenuesMON(EDB, year);
        }
        
        public System.Threading.Tasks.Task<Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesMONOutput> GetAnnualRevenuesMONAsync(string EDB, string year) {
            return base.Channel.GetAnnualRevenuesMONAsync(EDB, year);
        }
        
        public Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesFZOOutput GetAnnualRevenuesFZO(string EDB, string year) {
            return base.Channel.GetAnnualRevenuesFZO(EDB, year);
        }
        
        public System.Threading.Tasks.Task<Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesFZOOutput> GetAnnualRevenuesFZOAsync(string EDB, string year) {
            return base.Channel.GetAnnualRevenuesFZOAsync(EDB, year);
        }
        
        public Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesKKKSOutput GetAnnualRevenuesKKKS(string EDB, string year) {
            return base.Channel.GetAnnualRevenuesKKKS(EDB, year);
        }
        
        public System.Threading.Tasks.Task<Interop.CC.Portal.API.UJPDataForAnnualRevenues.AnnualRevenuesKKKSOutput> GetAnnualRevenuesKKKSAsync(string EDB, string year) {
            return base.Channel.GetAnnualRevenuesKKKSAsync(EDB, year);
        }
    }
}
